SELECT 
CAST(DRIVER_ID AS VARCHAR(45)) AS DRIVER_ID,
CAST(FIRST_NAME AS VARCHAR(45)) AS FIRST_NAME,
CAST(LAST_NAME AS VARCHAR(45)) AS LAST_NAME,
CAST(HIRE_DATE AS DATE) AS HIRE_DATE,
CAST(TERMINATION_DATE AS DATE) AS TERMINATION_DATE,
CAST(LICENSE_NUMBER AS VARCHAR(45)) AS LICENSE_NUMBER,
CAST(LICENSE_STATE AS VARCHAR(2)) AS LICENSE_STATE,
CAST(DATE_OF_BIRTH AS DATE) AS DATE_OF_BIRTH,
CAST(HOME_TERMINAL AS VARCHAR(45)) AS HOME_TERMINAL,
CAST(EMPLOYMENT_STATUS AS VARCHAR(45)) AS EMPLOYMENT_STATUS,
CAST(CDL_CLASS AS VARCHAR(45)) AS CDL_CLASS,
CAST(YEARS_EXPERIENCE as INTEGER) AS YEARS_EXPERIENCE,
cast(CreatedDate as timestamp) as CreatedDate,
cast(SourceSystem as varchar) as SourceSystem
FROM {{ source('sap', 'sap_logistics_drivers') }}
cross join (select current_timestamp() as CreatedDate) c
cross join (select 'SAP' as SourceSystem) s